### ISSUE TITLE
Could not access the Docker Image

### ISSUE THREAD

**Issue by PavanSai-39** [micronDLA/SDK#6]
The Docker Image and the Pico Computing Tools are pointing to the same Link. I am working on an Ubuntu System(16.04), can I get a proper Link from where I can get the Reuired Docker Image to complete my setup.

**Comment by Andrechang** [comment]
The docker image is being created. We'll let you know when we put it in the link

**Comment by PavanSai-39** [comment]
Yeah, thanks for that. But, is there any other way to complete the required setup and deploy the Deep learning models on the FPGA boards.
If there is any other way could you send me the link.

**Comment by circleme** [comment]
I also am looking for a docker image for this work as well.  Thank you, Andre.

**Comment by Andrechang** [comment]
The installer and the docker images are only way to setup and run on FPGA as they contain software to communicate with the FPGA.

The installer and the docker images are ready now.

You will have to request for them [here](https://picocomputing.zendesk.com/hc/en-us)
Once we receive your request, we will send you the necessary files for installation
