### ISSUE TITLE
ObjectDetection

### ISSUE THREAD

**Issue by kattamuruphani** [micronDLA/SDK#8]
The details on how to run an ImageClassification model is very clear and explained step by step, but unfortunately I was not able to find anything related on how to run ObjectDetection models. Please guide me to find if there are any instructions or please provide instructions if there aren't any. I tried to run ObjectDetection using the same instructions as provided for ImageClassification but I was not able to. I hope to hear from you soon.

**Comment by Andrechang** [comment]
we added new examples:
https://github.com/FWDNXT/SDK/tree/master/examples/pytorch-ssd
